### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhy/changeskin/SkinManager;

### ISSUE THREAD

**Issue by ghost** [hongyangAndroid/AndroidChangeSkin#7]
在 Application 中 初始化 出现上面这个错误

```
public class App extends Application{

    @Override
    public void onCreate() {
        super.onCreate();
        SkinManager.getInstance().init(this);
    }
}
```

log

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhy/changeskin/SkinManager;
                                                                 at com.dd.resttime.App.onCreate(App.java:16)
                                                                 at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:263)
                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1034)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605)
                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:148)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zhy.changeskin.SkinManager" on path: DexPathList[[zip file "/data/app/com.xx.xxxx-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
```

这是什么问题呢？

**Comment by ghost** [comment]
我重新新建了个project，这个问题又不存在了。。。。。。。
